### ISSUE TITLE
HTTPS?

### ISSUE THREAD

**Issue by cosmotek** [smarty/cproxy#6]
How can I serve HTTPS requests? The basic example doesn't appear to support it.

**Comment by mdwhatcott** [comment]
Have you tried [`http.ListenAndServeTLS`](https://pkg.go.dev/net/http#ListenAndServeTLS)?

**Comment by cosmotek** [comment]
> Have you tried [`http.ListenAndServeTLS`](https://pkg.go.dev/net/http#ListenAndServeTLS)?

Wouldn't that require some certs? I thought this would be using the certs of the destination website.

**Comment by cosmotek** [comment]
@mdwhatcott I'm looking for some way to forward proxy HTTPS traffic transparently without having to set up certs.

**Comment by joliver** [comment]
This is an `HTTP CONNECT` proxy which means that the client sets up a plaintext HTTP connection to the proxy and then through the proxy sets up a TLS/HTTPS connection.

In other words, you only use `ListenAndServe`.

**Comment by cosmotek** [comment]
> This is an `HTTP CONNECT` proxy which means that the client sets up a plaintext HTTP connection to the proxy and then through the proxy sets up a TLS/HTTPS connection.
> 
> In other words, you only use `ListenAndServe`.

@joliver Wouldn't this request some sort of special configuration on the client side? Im hoping to use this for a transparent proxy within a VPC. Ideally the client doesn't know anything, and private DNS is used to force communication with specific websites through the proxy.

**Comment by cosmotek** [comment]
<img width="719" alt="image" src="https://github.com/smarty/cproxy/assets/54327825/89db7c73-de9a-4f5a-b515-1f0c896e6445">

AFAIK: This doesn't work because curl is expecting the initial communication to be HTTPS

**Comment by joliver** [comment]
The client does need to be aware that it’s tunneling through the proxy.

curl has a —proxy option for this.

**Comment by cosmotek** [comment]
> The client does need to be aware that it’s tunneling through the proxy.
> 
> curl has a —proxy option for this.

@joliver Dang. Is there any workaround?

**Comment by joliver** [comment]
Negative. That’s the point of an HTTP CONNECT proxy.

If you want something transparent, it sounds like you want HAProxy or Nginx.

**Comment by cosmotek** [comment]
Thanks for the info.
